### ISSUE TITLE
Error from daemon.script

### ISSUE THREAD

**Issue by XoraKJoken** [moriakaice/bitburner#1]
I get this error pretty regularly from daemon.script. Is this something I'm doing wrong? 

Script runtime error: 
Server Ip: 75.4.7.9
Script name: daemon.script
Args:[zeus-med, 2178623817.1875, 75, 25, 806]
variable round not defined (Line 106)

**Comment by TheCodeDr** [comment]
New documentation for Netscript. Round is no longer defined. Replace with:
```javascript
Math.round( )
```
